Repository jenkins-infra/jenkins-infra, pull requests merged in 2020-10, with the labels that each got.

#1546 MATLAB Plugin page redirect
  dist/profile/templates/confluence/vhost.conf
Labels: hacktoberfest

#1549 hacktoberfest: Redirect "Purge Job History Plugin" from wiki to plugins site
  dist/profile/templates/confluence/vhost.conf
Labels: hacktoberfest

#1552 Redirect 'PlasticSCM Plugin' page from wiki to plugins site
  dist/profile/templates/confluence/vhost.conf
Labels: hacktoberfest

#1554 Redirect 'GitHub API Plugin' from wiki to plugins site
  dist/profile/templates/confluence/vhost.conf
Labels: hacktoberfest

#1553 Redirect 'Amazon Web Services SDK library' from wiki to plugins site
  dist/profile/templates/confluence/vhost.conf
Labels: hacktoberfest

#1590 Add redirects to plugin site
  dist/profile/templates/confluence/vhost.conf
Labels: hacktoberfest, hacktoberfest-accepted

#1588 hacktoberfest: migrate diagnosing errors wiki to github
  dist/profile/templates/confluence/vhost.conf
Labels: hacktoberfest-accepted
